language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

php:
  - 5.6
  - 7
  - hhvm
  
before_install:
  - composer self-up
  - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN

install:
  - composer update --no-interaction --prefer-stable $PREFER_LOWEST

script:
  - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

matrix:
  fast_finish: true
