language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

php:
  - 5.6
  - 7
  - hhvm

install:
  - composer update --dev --no-interaction --prefer-stable $PREFER_LOWEST

script:
  - ./vendor/bin/phpunit -c tests --coverage-clover=build/logs/clover.xml

matrix:
  fast_finish: true
