language: php

sudo: false

git:
  depth: 2

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - PREFER_LOWEST=""
    - PREFER_LOWEST="--prefer-lowest"

php:
  - 7.1
  - 7.0
  - 5.6
  - nightly
  - hhvm
  
before_install:
  - composer self-up
  - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN

install:
  - composer update --no-interaction --prefer-stable --no-suggest $PREFER_LOWEST

script:
  - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
  - ./vendor/bin/behat -f progress
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

matrix:
  fast_finish: true
