<?php

namespace Fabiang\DoctrineDynamic\Mapper;

use PHPUnit\Framework\TestCase;
use Doctrine\ORM\Mapping\ClassMetadataInfo;
use Fabiang\DoctrineDynamic\ConfigurationFactory;
use Fabiang\DoctrineDynamic\Behat\NamespaceOne\Entity\TestEntity as TestEntityOne;
use Fabiang\DoctrineDynamic\Behat\NamespaceTwo\Entity\TestEntity as TestEntityTwo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-05 at 16:21:50.
 *
 * @coversDefaultClass Fabiang\DoctrineDynamic\Mapper\MetadataMapper
 */
final class MetadataMapperTest extends TestCase
{
    /**
     * @var MetadataMapper
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MetadataMapper;
    }

    /**
     * @dataProvider provideConfig
     * @covers ::map
     * @covers Fabiang\DoctrineDynamic\ConfigurationFactory
     * @covers Fabiang\DoctrineDynamic\Configuration
     * @covers Fabiang\DoctrineDynamic\Configuration\Entity
     * @covers Fabiang\DoctrineDynamic\Configuration\Field
     * @covers Fabiang\DoctrineDynamic\Configuration\Mapping\JoinColumn
     * @covers Fabiang\DoctrineDynamic\Configuration\Mapping\JoinTable
     * @covers Fabiang\DoctrineDynamic\Configuration\Mapping\ManyToMany
     * @covers Fabiang\DoctrineDynamic\Configuration\Mapping\ManyToOne
     * @covers Fabiang\DoctrineDynamic\Configuration\Mapping\OneToMany
     * @covers Fabiang\DoctrineDynamic\Configuration\Mapping\OneToOne
     */
    public function testMap($config)
    {
        $metadata = $this->prophesize(ClassMetadataInfo::class);
        $metadata->mapOneToOne([
            'fieldName'    => 'oneToOneField',
            'targetEntity' => TestEntityTwo::class,
            'inversedBy'   => 'test',
            'mappedBy'     => null,
            'joinColumns'  => [
                [
                    'name' => 'test_id',
                    'referencedColumnName' => 'id',
                ]
            ]
        ])->shouldBeCalled();

        $metadata->mapManyToOne([
            'fieldName'    => 'manyToOneField',
            'targetEntity' => TestEntityOne::class,
            'inversedBy'   => 'test2',
            'joinColumns'  => [
                [
                    'name' => 'test2_id',
                    'referencedColumnName' => 'id',
                ]
            ]
        ])->shouldBeCalled();

        $metadata->mapOneToMany([
            'fieldName'    => 'oneToManyField',
            'targetEntity' => TestEntityTwo::class,
            'mappedBy'     => 'test3',
        ])->shouldBeCalled();

        $metadata->mapManyToMany([
            'fieldName'    => 'manyToManyField',
            'targetEntity' => TestEntityTwo::class,
            'inversedBy'   => 'test4',
            'mappedBy'     => null,
            'joinTable'    => [
                'name' => 'ManyToManyTableName',
            ]
        ])->shouldBeCalled();

        $configurationFactory = new ConfigurationFactory();
        $configuration        = $configurationFactory->factory($config);

        $metadataInstance = $metadata->reveal();
        $this->object->map(
            $metadataInstance,
            $configuration->get('MyNamespace\\Entity\\TestEntity')
        );

        $this->assertSame(
            'MyNamespace\\Repository\\TestRepository',
            $metadataInstance->customRepositoryClassName
        );
    }

    public function provideConfig()
    {
        return [
            [
                'config' => [
                    'MyNamespace\\Entity\\TestEntity' => [
                        'options' => [
                            'repository' => 'MyNamespace\\Repository\\TestRepository',
                        ],
                        'fields'  => [
                            'oneToOneField'  => [
                                'oneToOne' => [
                                        [
                                        'targetEntity' => TestEntityTwo::class,
                                        'inversedBy'   => 'test',
                                        'joinColumns'  => [
                                            'name'                 => 'test_id',
                                            'referencedColumnName' => 'id'
                                        ]
                                    ]
                                ]
                            ],
                            'manyToOneField' => [
                                'manyToOne' => [
                                    [
                                        'targetEntity' => TestEntityOne::class,
                                        'inversedBy'   => 'test2',
                                        'joinColumns'  => [
                                            'name'                 => 'test2_id',
                                            'referencedColumnName' => 'id'
                                        ]
                                    ]
                                ]
                            ],
                            'oneToManyField' => [
                                'oneToMany' => [
                                    [
                                        'targetEntity' => TestEntityTwo::class,
                                        'mappedBy'     => 'test3',
                                    ]
                                ]
                            ],
                            'manyToManyField' => [
                                'manyToMany' => [
                                    [
                                        'targetEntity' => TestEntityTwo::class,
                                        'inversedBy'   => 'test4',
                                        'joinTable'    => [
                                            'name' => 'ManyToManyTableName',
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ];
    }
}
